Version: 0.1
phases:
  install:
    commands:
      - echo $test
      - npm install time
      - aws cloudformation package --template-file samTemplate1.yaml --s3-bucket testlambdact 
                                   --output-template-file NewSamTemplate.yaml
      - aws cloudformation package --template-file samTemplate2.yaml --s3-bucket testlambdact
                                   --output-template-file NewSamTemplate2.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
    - NewSamTemplate2.yaml
