WSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction6:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index6.handler
      Runtime: nodejs4.3
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource6
            Method: GET
  MyAPI:
    Type: AWS::Serverless::API
    Properties:
      StageName: prod
Outputs:
  RestAPI:
    Description: The ID of the RestAPI
    Value: !Ref MyAPI
    Export:
      Name: !Sub "${AWS::StackName}-RestAPI"
