swagger: "2.0"
info:
  version: "1.0"
  title: "MyBetaStack"
host: "qnh2ydtt0g.execute-api.us-west-2.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /TimeResource:
    get:
  /TimeResource6:
    get:
